first_name: Kuk Jin
last_name: Jang
email: jangkj@seas.upenn.edu

linkedin_username: kuk-jin-jang-9a971014
research_gate_profile: Kuk-Jang
scholar_userid: HFajZtgAAAAJ

description: >
  Machine Learning Researcher for Trustworthy AI.
content_note: >
  Feel free to reach out through email.

nav_links:
  - href: /
    label: about
    new_tab: false
  - href: /publications
    label: publications
    new_tab: false
  - href: /cv.pdf
    label: CV
    new_tab: true

affiliation:
  name: PRECISE University of Pennsylvania
  url: https://precise.seas.upenn.edu/
