first_name: Kuk Jin
last_name: Jang
email: jangkj@seas.upenn.edu

linkedin_username: kuk-jin-jang-9a971014
research_gate_profile: Kuk-Jang
scholar_userid: HFajZtgAAAAJ

description: >
  Machine Learning Researcher for Trustworthy AI.
content_note: >
  Feel free to reach out through email.
